In [2]:
## importing essential packages
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
# Load the dataset
df = pd.read_csv("Precily_Text_Similarity.csv")

In [4]:
df.head()

text1  \
0  broadband challenges tv viewing the number of ...   
1  rap boss arrested over drug find rap mogul mar...   
2  player burn-out worries robinson england coach...   
3  hearts of oak 3-2 cotonsport hearts of oak set...   
4  sir paul rocks super bowl crowds sir paul mcca...   

                                               text2  
0  gardener wins double in glasgow britain s jaso...  
1  amnesty chief laments war failure the lack of ...  
2  hanks greeted at wintry premiere hollywood sta...  
3  redford s vision of sundance despite sporting ...  
4  mauresmo opens with victory in la amelie maure...

In [5]:
df.shape

(3000, 2)

In [6]:
## Checking whether there is any null values in the data
print(df.isnull().sum())

text1    0
text2    0
dtype: int64


## now we are going generate sentence embeddings

In [7]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')


In [8]:
sentence_pairs = df[["text1", "text2"]].values
print(sentence_pairs)

[['broadband challenges tv viewing the number of europeans with broadband has exploded over the past 12 months  with the web eating into tv viewing habits  research suggests.  just over 54 million people are hooked up to the net via broadband  up from 34 million a year ago  according to market analysts nielsen/netratings. the total number of people online in europe has broken the 100 million mark. the popularity of the net has meant that many are turning away from tv  say analysts jupiter research. it found that a quarter of web users said they spent less time watching tv in favour of the net  the report by nielsen/netratings found that the number of people with fast internet access had risen by 60% over the past year.  the biggest jump was in italy  where it rose by 120%. britain was close behind  with broadband users almost doubling in a year. the growth has been fuelled by lower prices and a wider choice of always-on  fast-net subscription plans.  twelve months ago high speed intern

In [9]:
embeddings1, embeddings2 = [], []
for i in range(len(df)):
  new_embedding1 = model.encode(df['text1'][i])
  embeddings1.append(new_embedding1)
  new_embedding2 = model.encode(df['text2'][i])
  embeddings2.append(new_embedding2)


In [10]:
cos_sim=util.cos_sim(embeddings1,embeddings2)
cos_sim

c:\Users\shitk2\Anaconda3\envs\my_env\lib\site-packages\sentence_transformers\util.py:36: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_new.cpp:233.)
  a = torch.tensor(a)


tensor([[ 0.0732,  0.0711,  0.1144,  ..., -0.0036, -0.0059,  0.1241],
        [ 0.1831,  0.1815,  0.0932,  ..., -0.0365,  0.1235,  0.2207],
        [ 0.0915,  0.1337,  0.2231,  ..., -0.0416,  0.3344,  0.2448],
        ...,
        [ 0.1492,  0.2136,  0.1041,  ...,  0.0743,  0.3868,  0.1726],
        [ 0.1849, -0.0017,  0.1007,  ..., -0.0299,  0.0694,  0.2415],
        [-0.0906,  0.0777,  0.0799,  ...,  0.1665,  0.0606, -0.0392]])

In [11]:
cosine_similarities = cosine_similarity(embeddings1, embeddings2)

In [12]:
similarity_scores = cosine_similarities.reshape(-1)

In [13]:
similarity_scores

array([ 0.07324862,  0.0710762 ,  0.11435704, ...,  0.16651015,
        0.06063753, -0.03916519], dtype=float32)

## testing with the test data

In [23]:
test_embeddings1=model.encode(df['text1'][2076])
test_embeddings2=model.encode(df['text2'][2056])

In [24]:
cosine_similarities = util.cos_sim(test_embeddings1,test_embeddings2)

In [25]:
cosine_similarities[0]

tensor([0.1856])